package Mobipunkt.OstmineTest;

// Generated by Selenium IDE

import org.junit.After;
import org.junit.Before;
import org.junit.Test;
import org.openqa.selenium.By;
import org.openqa.selenium.Dimension;
import org.openqa.selenium.JavascriptExecutor;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.chrome.ChromeDriver;


public class MobipunktOstmineTest {
    private WebDriver driver;
    private JavascriptExecutor js;

    @Before
    public void setUp() {
        driver = new ChromeDriver();
        js = (JavascriptExecutor) driver;
    }

    @After
    public void tearDown() {
        driver.quit();
    }

    @Test
    public void mobipunktOstmineTest() {
        driver.get("https://www.mobipunkt.ee/");
        driver.manage().window().setSize(new Dimension(1680, 955));
        driver.findElement(By.cssSelector(".unslider-active > #hero > #heroimage .heroflex")).click();
        driver.findElement(By.cssSelector(".col1:nth-child(3) .product-image")).click();
        driver.findElement(By.cssSelector(".blue-button")).click();
        driver.findElement(By.cssSelector(".membutton:nth-child(5)")).click();
        driver.findElement(By.cssSelector(".membutton:nth-child(6)")).click();
        driver.findElement(By.cssSelector(".membutton:nth-child(7)")).click();
        driver.findElement(By.cssSelector(".membutton:nth-child(8)")).click();
        driver.findElement(By.cssSelector(".membutton:nth-child(9)")).click();
        driver.findElement(By.cssSelector(".membutton:nth-child(5)")).click();
        js.executeScript("window.scrollTo(0,383)");
        js.executeScript("window.scrollTo(0,437)");
        driver.findElement(By.cssSelector(".rdivider:nth-child(4)")).click();
        driver.findElement(By.cssSelector(".rdivider:nth-child(4) > .topmargins2")).click();
        driver.findElement(By.id("addtocart")).click();
        driver.findElement(By.linkText("Äriklient")).click();
        driver.findElement(By.name("name")).click();
        driver.findElement(By.id("email2")).click();
        driver.findElement(By.id("email2")).sendKeys("Adadsa@asdsa.com");
        driver.findElement(By.cssSelector(".blue-button4")).click();
        driver.findElement(By.linkText("iPad")).click();
        driver.findElement(By.cssSelector(".disambugation:nth-child(6) > .disambiguation-message > .alates-a")).click();
        driver.findElement(By.linkText("alates €445.00 ›")).click();
        driver.findElement(By.cssSelector(".blue-button")).click();
        driver.findElement(By.cssSelector(".membutton:nth-child(5)")).click();
        driver.findElement(By.cssSelector(".membutton:nth-child(7)")).click();
        driver.findElement(By.cssSelector(".rdivider:nth-child(4) > .topmargins2")).click();
        driver.findElement(By.id("addtocart")).click();
        driver.findElement(By.linkText("Remont")).click();
        driver.findElement(By.cssSelector(".on-off:nth-child(4)")).click();
        driver.findElement(By.id("remont1")).click();
        driver.findElement(By.id("cartbutton")).click();
        driver.findElement(By.cssSelector(".blue-button-g")).click();
        driver.findElement(By.id("r2")).click();
        driver.findElement(By.id("r444")).click();
        driver.findElement(By.cssSelector(".radioholder:nth-child(6)")).click();
        driver.findElement(By.name("jm")).click();
    }
}

