package Mobipunkt.TradeInTest;// Generated by Selenium IDE

import org.junit.After;
import org.junit.Before;
import org.junit.Test;
import org.openqa.selenium.By;
import org.openqa.selenium.Dimension;
import org.openqa.selenium.JavascriptExecutor;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.chrome.ChromeDriver;

import java.util.HashMap;
import java.util.Map;

public class MobipunktTradeInTest {
    JavascriptExecutor js;
    private WebDriver driver;
    private Map<String, Object> vars;

    @Before
    public void setUp() {
        driver = new ChromeDriver();
        js = (JavascriptExecutor) driver;
        vars = new HashMap<>();
    }

    @After
    public void tearDown() {
        driver.quit();
    }

    @Test
    public void tradeInTest() {
        driver.get("https://www.mobipunkt.ee/");
        driver.manage().window().setSize(new Dimension(1680, 955));
        driver.findElement(By.linkText("Vana seade uueks")).click();
        driver.findElement(By.name("telefon")).click();
        driver.findElement(By.name("telefon")).sendKeys("asdsadas");
        driver.findElement(By.name("email")).click();
        driver.findElement(By.name("email")).sendKeys("adsadsda@dsa");
        driver.findElement(By.cssSelector(".blue-button")).click();
    }
}
